### ISSUE TITLE
Is there a screenshot or example of what a status looks like?

### ISSUE THREAD

**Issue by alex-page** [Sibz/github-status-action#16]
I might be really silly but I tried implementing this and couldn't get anything to show up in checks. I wanted to make a link to a deployed URL following this pattern https://github.com/jsmrcaga/action-netlify-deploy#use-branch-name-to-deploy

The action is passing but I cannot see the status.

**Comment by alex-page** [comment]
I messed up the pull request part 🤦‍♂️. Thanks for this awesome action.

What fixed my problem, maybe this could be the default?
```
          sha: ${{github.event.pull_request.head.sha || github.sha}}
```

**Comment by Sibz** [comment]
Hi thanks for the feedback.

I am not sure if changing this default would be breaking for existing users who don't have this triggering on a pull.

I would have to write up a test to find out, currently my project plate is full but I'll add it as a TODO.
