### ISSUE TITLE
Owner Regex patterns from source code and dist directory do not match

### ISSUE THREAD

**Issue by peter-murray** [Sibz/github-status-action#32]
On the `1.1.6` version of this action, the validation regex patterns are not consistent between the source code and what is present in the `dist` directory which is what the action uses when executing.

* https://github.com/Sibz/github-status-action/blob/v1.1.6/dist/index.js#L5744
* https://github.com/Sibz/github-status-action/blob/v1.1.6/src/makeStatusRequest.ts#L10

This is currently failing for me on a valid owner name that has the form `Contoso-Hotels-Security`, which this passes with the regex in the source code but not the one in the `dist` directory.

**Comment by maxisam** [comment]
ah.... I have this issue as well. Thanks for discovering this.

**Comment by david-all-win-software** [comment]
I have this issue as well. It seems the release version is not generated, the regex of the source code is fine but the one that remains in dist is wrong
